### ISSUE TITLE
Пожалуйста помогите с настройкой и размером шрифта.

### ISSUE THREAD

**Issue by DisturbedChif** [Schmarotzer/Afterlife-RUS#1]
Добрый день. Помогите пожалуйста с настройкой шрифта локализации. Можно ли как то уменьшить шрифт чтобы он не выходил за поля?
![изображение_2024-10-23_125343010](https://github.com/user-attachments/assets/afc97ba8-8ffe-4a39-b373-bf0b9415b18e)

**Comment by Schmarotzer** [comment]
Вам надо файл fonts.unity3d из папки с русификатором поместить в папку мода Afterlife (с заменой).
